2025-03-06 15:45:55,605 INFO    MainThread:28204 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-06 15:45:55,606 INFO    MainThread:28204 [wandb_setup.py:_flush():67] Configure stats pid to 28204
2025-03-06 15:45:55,606 INFO    MainThread:28204 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Amar\.config\wandb\settings
2025-03-06 15:45:55,606 INFO    MainThread:28204 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Amar\Desktop\MTech\2nd sem\DL\assign_1\da6401_assignment1\wandb\settings
2025-03-06 15:45:55,606 INFO    MainThread:28204 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-06 15:45:55,607 INFO    MainThread:28204 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Amar\Desktop\MTech\2nd sem\DL\assign_1\da6401_assignment1\wandb\run-20250306_154555-6a9n43xk\logs\debug.log
2025-03-06 15:45:55,607 INFO    MainThread:28204 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Amar\Desktop\MTech\2nd sem\DL\assign_1\da6401_assignment1\wandb\run-20250306_154555-6a9n43xk\logs\debug-internal.log
2025-03-06 15:45:55,607 INFO    MainThread:28204 [wandb_init.py:init():761] calling init triggers
2025-03-06 15:45:55,607 INFO    MainThread:28204 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'DA6401_assign_2', 'wandb_entity': 'amar74384-iit-madras', 'dataset': 'fashion_mnist', 'epochs': 1, 'batch_size': 4, 'loss': 'cross_entropy', 'optimizer': 'sgd', 'learning_rate': 0.1, 'momentum': 0.5, 'beta': 0.5, 'beta1': 0.5, 'beta2': 0.5, 'epsilon': 1e-06, 'weight_decay': 0.0, 'weight_init': 'random', 'num_layers': 1, 'hidden_size': 4, 'activation': 'sigmoid', '_wandb': {}}
2025-03-06 15:45:55,608 INFO    MainThread:28204 [wandb_init.py:init():784] starting backend
2025-03-06 15:45:55,608 INFO    MainThread:28204 [wandb_init.py:init():788] sending inform_init request
2025-03-06 15:45:55,772 INFO    MainThread:28204 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-06 15:45:55,774 INFO    MainThread:28204 [wandb_init.py:init():803] backend started and connected
2025-03-06 15:45:55,778 INFO    MainThread:28204 [wandb_init.py:init():896] updated telemetry
2025-03-06 15:45:55,904 INFO    MainThread:28204 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-06 15:45:56,930 INFO    MainThread:28204 [wandb_init.py:init():995] starting run threads in backend
2025-03-06 15:45:58,401 INFO    MainThread:28204 [wandb_run.py:_console_start():2377] atexit reg
2025-03-06 15:45:58,401 INFO    MainThread:28204 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-06 15:45:58,401 INFO    MainThread:28204 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-06 15:45:58,401 INFO    MainThread:28204 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-06 15:45:58,407 INFO    MainThread:28204 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-06 15:45:58,412 WARNING MsgRouterThr:28204 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Amar\anaconda3\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amar\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amar\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Amar\anaconda3\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amar\anaconda3\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-06 15:45:58,416 INFO    MsgRouterThr:28204 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
